import type { Question } from './types'

export const SCHEMA_VERSION = '1.0'

/**
 * The questionnaire. Order here is the order shown to participants.
 * Keep ids stable: they are the contract with the evaluation agent.
 * See docs/KONZEPT.md for the rationale behind each item.
 */
export const questions: Question[] = [
  {
    id: 'q00_nickname',
    block: '0',
    type: 'text',
    label: 'Name',
    title: 'Wie sollen wir dich nennen?',
    hint: 'Ein Spitzname reicht. Nur der Host sieht ihn.',
    emoji: '👋',
    placeholder: 'z. B. Chris',
    maxLength: 30,
    required: true,
    aggregation: 'none',
  },
  {
    id: 'q01_energy',
    block: 'A',
    type: 'scale',
    label: 'Energie',
    title: 'Wie viel Energie hast du heute Abend?',
    emoji: '🔋',
    min: 1,
    max: 5,
    stepEmojis: ['🛋️', '🐢', '🙂', '⚡', '🚀'],
    stepLabels: ['Sofa-Modus', 'Eher ruhig', 'Normal', 'Gut drauf', 'Vollgas'],
    required: true,
    aggregation: 'least_misery',
  },
  {
    id: 'q02_mood',
    block: 'A',
    type: 'scale',
    label: 'Stimmung',
    title: 'Wie ist deine Stimmung gerade?',
    emoji: '🌤️',
    min: 1,
    max: 5,
    stepEmojis: ['😩', '😕', '😐', '🙂', '😄'],
    stepLabels: ['Mies', 'Geht so', 'Okay', 'Gut', 'Super'],
    required: true,
    aggregation: 'median',
  },
  {
    id: 'q03_motives',
    block: 'A',
    type: 'rank',
    label: 'Motive',
    title: 'Was soll dir der Abend heute vor allem geben?',
    hint: 'Tippe die vier in deiner Reihenfolge an. Das Wichtigste zuerst.',
    emoji: '🎯',
    options: [
      { value: 'avoid', label: 'Abschalten', emoji: '🧘', description: 'Runterkommen, Kopf frei, nichts müssen' },
      { value: 'social', label: 'Leute', emoji: '🗣️', description: 'Quatschen, lachen, Zeit miteinander' },
      { value: 'master', label: 'Was schaffen', emoji: '🏆', description: 'Mich messen, gewinnen, etwas hinkriegen' },
      { value: 'explore', label: 'Was entdecken', emoji: '💡', description: 'Neues lernen, kreativ sein, staunen' },
    ],
    required: true,
    aggregation: 'borda',
  },
  {
    id: 'q04_time',
    block: 'B',
    type: 'single',
    label: 'Zeit',
    title: 'Wie viel Zeit hast du?',
    emoji: '⏱️',
    options: [
      { value: 'short', label: 'Bis ca. 2 Stunden' },
      { value: 'medium', label: '2 bis 4 Stunden' },
      { value: 'open', label: 'Open End' },
    ],
    required: true,
    aggregation: 'least_misery',
  },
  {
    id: 'q05_budget',
    block: 'B',
    type: 'single',
    label: 'Budget',
    title: 'Was darf es dich heute kosten?',
    hint: 'Pro Person.',
    emoji: '💸',
    options: [
      { value: 'free', label: 'Am liebsten nichts' },
      { value: 'low', label: 'Bis 15 €' },
      { value: 'mid', label: 'Bis 40 €' },
      { value: 'any', label: 'Egal, wir gönnen uns' },
    ],
    required: true,
    aggregation: 'least_misery',
  },
  {
    id: 'q06_indoor',
    block: 'B',
    type: 'single',
    label: 'Drinnen/Draußen',
    title: 'Drinnen oder draußen?',
    emoji: '🏠',
    options: [
      { value: 'indoor', label: 'Drinnen', emoji: '🛋️' },
      { value: 'outdoor', label: 'Draußen', emoji: '🌳' },
      { value: 'any', label: 'Egal', emoji: '🤷' },
    ],
    required: true,
    aggregation: 'least_misery',
  },
  {
    id: 'q07_distance',
    block: 'B',
    type: 'single',
    label: 'Fahrweite',
    title: 'Wie weit würdest du heute fahren?',
    emoji: '🚌',
    options: [
      { value: 'stay', label: 'Ich bleib am liebsten, wo ich bin' },
      { value: '15', label: 'Bis 15 Minuten' },
      { value: '45', label: 'Bis 45 Minuten' },
      { value: 'any', label: 'Ist mir egal' },
    ],
    required: true,
    aggregation: 'least_misery',
  },
  {
    id: 'q08_car',
    block: 'B',
    type: 'single',
    label: 'Auto',
    title: 'Hast du heute ein Auto dabei?',
    emoji: '🚗',
    options: [
      { value: 'yes', label: 'Ja' },
      { value: 'no', label: 'Nein' },
    ],
    required: true,
    aggregation: 'union',
  },
  {
    id: 'q09_novelty',
    block: 'C',
    type: 'scale',
    label: 'Neu vs. Vertraut',
    title: 'Was Bekanntes oder was Neues?',
    emoji: '🧭',
    min: 1,
    max: 5,
    poles: ['Was Bewährtes, das sicher klappt', 'Was Neues ausprobieren'],
    required: true,
    aggregation: 'average',
  },
  {
    id: 'q10_challenge',
    block: 'C',
    type: 'scale',
    label: 'Anspruch',
    title: 'Berieseln lassen oder gefordert werden?',
    emoji: '🧠',
    min: 1,
    max: 5,
    poles: ['Einfach genießen, Hirn aus', 'Richtig gefordert werden'],
    required: true,
    aggregation: 'average',
  },
  {
    id: 'q11_active',
    block: 'C',
    type: 'single',
    label: 'Selbst/Zuschauen',
    title: 'Selbst machen oder zuschauen?',
    emoji: '🎭',
    options: [
      { value: 'active', label: 'Selbst aktiv sein', emoji: '🙌' },
      { value: 'passive', label: 'Zuschauen, konsumieren', emoji: '🍿' },
      { value: 'mix', label: 'Mix ist fein', emoji: '🔀' },
    ],
    required: true,
    aggregation: 'average',
  },
  {
    id: 'q12_talk',
    block: 'C',
    type: 'single',
    label: 'Redeanteil',
    title: 'Wie viel Reden darf es sein?',
    emoji: '💬',
    options: [
      { value: 'main', label: 'Reden ist das Hauptprogramm' },
      { value: 'side', label: 'Nebenbei reden reicht' },
      { value: 'quiet', label: 'Kann auch mal still sein' },
    ],
    required: true,
    aggregation: 'average',
  },
  {
    id: 'q13_nogo',
    block: 'D',
    type: 'multi',
    label: 'No-Gos',
    title: 'Was geht heute für dich gar nicht?',
    hint: 'Alles ankreuzen, was zutrifft. Ein No-Go schlägt fünf Jas.',
    emoji: '🚫',
    exclusiveValue: 'none',
    options: [
      { value: 'alcohol', label: 'Alkohol', emoji: '🍺' },
      { value: 'loud', label: 'Laute Orte, Menschenmassen', emoji: '📢' },
      { value: 'sweat', label: 'Schwitzen, Sport', emoji: '🏃' },
      { value: 'screen', label: 'Bildschirm (Film, Games)', emoji: '📺' },
      { value: 'cook', label: 'Selber kochen', emoji: '🍳' },
      { value: 'boardgames', label: 'Brett- und Kartenspiele', emoji: '🎲' },
      { value: 'culture', label: 'Kultur (Museum, Theater, Lesung)', emoji: '🎭' },
      { value: 'travel', label: 'Lange Anfahrt', emoji: '🛣️' },
      { value: 'stage', label: 'Vorne stehen (Karaoke, Impro)', emoji: '🎤' },
      { value: 'none', label: 'Nichts davon', emoji: '✅' },
    ],
    freeText: { placeholder: 'Sonst noch was? Allergie, Verletzung, …' },
    required: false,
    aggregation: 'union',
  },
  {
    id: 'q14_categories',
    block: 'D',
    type: 'multi',
    label: 'Kategorien',
    title: 'Worauf hättest du heute grundsätzlich Bock?',
    hint: 'Kreuz alles an, was für dich okay wäre.',
    emoji: '✨',
    min: 1,
    options: [
      { value: 'eat_out', label: 'Essen gehen', emoji: '🍽️' },
      { value: 'cook', label: 'Zusammen kochen', emoji: '🍳' },
      { value: 'boardgames', label: 'Brett- und Kartenspiele', emoji: '🎲' },
      { value: 'videogames', label: 'Videospiele', emoji: '🎮' },
      { value: 'film', label: 'Film oder Serie', emoji: '🎬' },
      { value: 'bar', label: 'Bar, Kneipe', emoji: '🍻' },
      { value: 'culture', label: 'Kino, Konzert, Kultur', emoji: '🎟️' },
      { value: 'sport', label: 'Aktiv und sportlich', emoji: '🎳', description: 'Bowling, Bouldern, Minigolf …' },
      { value: 'experience', label: 'Erlebnis', emoji: '🔐', description: 'Escape Room, Lasertag, Quiz-Night …' },
      { value: 'outdoor', label: 'Draußen', emoji: '🌳', description: 'Spaziergang, See, Grillen' },
      { value: 'creative', label: 'Kreatives', emoji: '🎨', description: 'Basteln, Musik, Malen' },
      { value: 'wellness', label: 'Wellness', emoji: '🧖', description: 'Sauna, Therme' },
      { value: 'chill', label: 'Einfach chillen und quatschen', emoji: '☕' },
    ],
    required: true,
    aggregation: 'approval',
  },
  {
    id: 'q15_joker',
    block: 'D',
    type: 'text',
    label: 'Joker',
    title: 'Joker: Wenn du heute allein entscheiden dürftest, was würden wir machen?',
    hint: 'Optional. Alles erlaubt.',
    emoji: '🃏',
    placeholder: 'Deine Idee …',
    multiline: true,
    maxLength: 280,
    required: false,
    aggregation: 'text',
  },
  {
    id: 'q16_flex',
    block: 'D',
    type: 'scale',
    label: 'Flexibilität',
    title: 'Wie flexibel bist du heute?',
    emoji: '🤸',
    min: 1,
    max: 5,
    poles: ['Ich hab klare Wünsche', 'Mir ist fast alles recht, Hauptsache zusammen'],
    required: true,
    aggregation: 'average',
  },
]

export const NICKNAME_ID = 'q00_nickname'
