import type { Question } from './types'

export const SCHEMA_VERSION = '2.0'

/**
 * The questionnaire, v2: psychological and projective rather than logistical.
 * The evaluation agent infers the activity from state, needs and imagery;
 * hard logistics (place, weather, cars) come from the host context.
 * Order here is the order shown. Keep ids stable: they are the contract
 * with the evaluation agent. See docs/KONZEPT.md for the rationale.
 */
export const questions: Question[] = [
  {
    id: 'q00_nickname',
    block: '0',
    type: 'text',
    label: 'Name',
    title: 'Wie sollen wir dich nennen?',
    hint: 'Ein Spitzname reicht. Nur der Host sieht ihn.',
    placeholder: 'z. B. Chris',
    maxLength: 30,
    required: true,
    aggregation: 'none',
  },

  // ---------- A · Innenwetter (aktueller Zustand) ----------
  {
    id: 'q01_weather',
    block: 'A',
    type: 'single',
    label: 'Innenwetter',
    title: 'Wenn dein heutiger Tag ein Wetter wäre, welches?',
    options: [
      { value: 'sun', label: 'Klarer Himmel', description: 'Leicht, hell, alles offen' },
      { value: 'clouds', label: 'Leicht bewölkt', description: 'Okay, nichts Besonderes' },
      { value: 'fog', label: 'Nebel', description: 'Dumpf, unklar, ich brauche Konturen' },
      { value: 'rain', label: 'Dauerregen', description: 'Schwer, müde, eher nach innen' },
      { value: 'storm', label: 'Gewitter', description: 'Geladen, gereizt, muss raus' },
      { value: 'humid', label: 'Schwül und windstill', description: 'Unruhig, aber ohne Richtung' },
    ],
    required: true,
    aggregation: 'union',
  },
  {
    id: 'q02_body',
    block: 'A',
    type: 'single',
    label: 'Körper',
    title: 'Wie fühlt sich dein Körper gerade an?',
    options: [
      { value: 'lead', label: 'Schwer wie Blei' },
      { value: 'tired_good', label: 'Angenehm müde' },
      { value: 'neutral', label: 'Unauffällig, funktioniert' },
      { value: 'restless', label: 'Unruhig, will sich bewegen' },
      { value: 'electric', label: 'Elektrisch, sprungbereit' },
    ],
    required: true,
    aggregation: 'least_misery',
  },
  {
    id: 'q03_social_battery',
    block: 'A',
    type: 'scale',
    label: 'Sozial-Akku',
    title: 'Wie voll ist dein Sozial-Akku?',
    hint: 'Wie viel Menschen, Gespräch und Reiz verträgst du heute noch?',
    min: 1,
    max: 5,
    poles: ['Fast leer, bitte wenig Input', 'Randvoll, her mit allen'],
    required: true,
    aggregation: 'least_misery',
  },
  {
    id: 'q04_head',
    block: 'A',
    type: 'scale',
    label: 'Kopf',
    title: 'Wie voll ist dein Kopf?',
    min: 1,
    max: 5,
    poles: ['Leer und offen', 'Randvoll, braucht Auslauf'],
    required: true,
    aggregation: 'median',
  },

  // ---------- B · Bedürfnis (was dahinter liegt) ----------
  {
    id: 'q05_missing',
    block: 'B',
    type: 'rank',
    label: 'Was fehlt',
    title: 'Was hat dir in den letzten Tagen am meisten gefehlt?',
    hint: 'Tippe die vier in deiner Reihenfolge an. Das Wichtigste zuerst.',
    options: [
      { value: 'connection', label: 'Nähe', description: 'Echte Gespräche, gesehen werden' },
      { value: 'autonomy', label: 'Selbstbestimmung', description: 'Etwas tun, weil ich es will, nicht muss' },
      { value: 'competence', label: 'Wirksamkeit', description: 'Etwas können, etwas hinbekommen' },
      { value: 'release', label: 'Nichts müssen', description: 'Loslassen, Kopf aus, keine Verantwortung' },
    ],
    required: true,
    aggregation: 'borda',
  },
  {
    id: 'q06_escape',
    block: 'B',
    type: 'multi',
    label: 'Weg von',
    title: 'Wovon willst du heute Abend weg?',
    hint: 'Alles ankreuzen, was zutrifft.',
    exclusiveValue: 'nothing',
    options: [
      { value: 'screens', label: 'Bildschirmen' },
      { value: 'people', label: 'Menschen' },
      { value: 'thoughts', label: 'Meinen eigenen Gedanken' },
      { value: 'routine', label: 'Der Routine' },
      { value: 'silence', label: 'Der Stille' },
      { value: 'performance', label: 'Leistung und Bewertung' },
      { value: 'decisions', label: 'Entscheidungen treffen' },
      { value: 'nothing', label: 'Nichts, mir geht es gut' },
    ],
    required: true,
    aggregation: 'union',
  },
  {
    id: 'q07_residue',
    block: 'B',
    type: 'single',
    label: 'Was bleibt',
    title: 'Was soll morgen früh von heute Abend übrig sein?',
    options: [
      { value: 'story', label: 'Eine Geschichte, die ich erzählen kann' },
      { value: 'rest', label: 'Ein ausgeruhter Kopf' },
      { value: 'closeness', label: 'Das Gefühl, dass wir uns nahe sind' },
      { value: 'achievement', label: 'Etwas, das ich gelernt oder geschafft habe' },
      { value: 'laughter', label: 'Lachmuskelkater' },
      { value: 'nothing', label: 'Nichts Besonderes, einfach ein guter Abend' },
    ],
    required: true,
    aggregation: 'approval',
  },

  // ---------- C · Form (wie der Abend sich anfühlen soll) ----------
  {
    id: 'q08_genre',
    block: 'C',
    type: 'single',
    label: 'Genre',
    title: 'Der heutige Abend als Film. Welches Genre?',
    options: [
      { value: 'comedy', label: 'Komödie', description: 'Leicht, laut, albern' },
      { value: 'roadmovie', label: 'Roadmovie', description: 'Unterwegs, offen, mal sehen, wo wir landen' },
      { value: 'thriller', label: 'Thriller', description: 'Spannung, Rätsel, Adrenalin' },
      { value: 'documentary', label: 'Doku', description: 'Neugier, etwas verstehen, staunen' },
      { value: 'feelgood', label: 'Feel-Good-Drama', description: 'Warm, nah, ehrlich' },
      { value: 'arthouse', label: 'Arthouse', description: 'Langsam, schön, ein bisschen seltsam' },
      { value: 'action', label: 'Action', description: 'Körper, Tempo, Schweiß' },
    ],
    required: true,
    aggregation: 'approval',
  },
  {
    id: 'q09_pace',
    block: 'C',
    type: 'single',
    label: 'Tempo',
    title: 'Welches Tempo hat der Abend?',
    options: [
      { value: 'stroll', label: 'Spaziergang', description: 'Gemächlich, ohne Ziel' },
      { value: 'brisk', label: 'Flotter Gang', description: 'Wach, aber entspannt' },
      { value: 'sprint', label: 'Sprint', description: 'Kurz und intensiv' },
      { value: 'marathon', label: 'Marathon mit Pausen', description: 'Lang, mit mehreren Stationen' },
    ],
    required: true,
    aggregation: 'least_misery',
  },
  {
    id: 'q10_surprise',
    block: 'C',
    type: 'scale',
    label: 'Überraschung',
    title: 'Willst du wissen, was kommt, oder überrascht werden?',
    min: 1,
    max: 5,
    poles: ['Ich will wissen, was kommt', 'Überrascht mich'],
    required: true,
    aggregation: 'average',
  },
  {
    id: 'q11_chaos',
    block: 'C',
    type: 'scale',
    label: 'Chaos',
    title: 'Wie viel darf heute schiefgehen?',
    min: 1,
    max: 5,
    poles: ['Nichts, bitte', 'Chaos willkommen'],
    required: true,
    aggregation: 'least_misery',
  },
  {
    id: 'q12_role',
    block: 'C',
    type: 'single',
    label: 'Rolle',
    title: 'Welche Rolle willst du heute in der Gruppe haben?',
    options: [
      { value: 'instigator', label: 'Anstifter', description: 'Ich bringe die Idee und ziehe' },
      { value: 'host', label: 'Gastgeber', description: 'Ich sorge dafür, dass es allen gut geht' },
      { value: 'player', label: 'Spielmacher', description: 'Ich will mitspielen, gewinnen, gestalten' },
      { value: 'follower', label: 'Mitläufer', description: 'Sagt mir, wo es hingeht, ich bin dabei' },
      { value: 'observer', label: 'Beobachter', description: 'Ich bin gern da, muss aber nicht im Zentrum sein' },
    ],
    required: true,
    aggregation: 'union',
  },

  // ---------- D · Rahmen und Joker ----------
  {
    id: 'q13_generosity',
    block: 'D',
    type: 'scale',
    label: 'Geld',
    title: 'Wie großzügig bist du heute mit Geld?',
    min: 1,
    max: 5,
    poles: ['Knapp, am liebsten gratis', 'Ich gönne mir was'],
    required: true,
    aggregation: 'least_misery',
  },
  {
    id: 'q14_length',
    block: 'D',
    type: 'single',
    label: 'Länge',
    title: 'Wie lang soll der Abend sein?',
    options: [
      { value: 'short', label: 'Ein kurzer Ausflug', description: 'Bis etwa zwei Stunden' },
      { value: 'evening', label: 'Ein ordentlicher Abend', description: 'Drei, vier Stunden' },
      { value: 'open', label: 'Open End' },
    ],
    required: true,
    aggregation: 'least_misery',
  },
  {
    id: 'q15_waste',
    block: 'D',
    type: 'multi',
    label: 'Verschwendet',
    title: 'Womit wäre der Abend für dich verschwendet?',
    hint: 'Das sind deine Vetos. Ein Veto schlägt fünf Jas.',
    exclusiveValue: 'nothing',
    options: [
      { value: 'sitting', label: 'Nur rumsitzen' },
      { value: 'crowds', label: 'Menschenmassen und Lärm' },
      { value: 'money', label: 'Viel Geld ausgeben' },
      { value: 'exertion', label: 'Körperliche Anstrengung' },
      { value: 'travel', label: 'Lange Anfahrt' },
      { value: 'smalltalk', label: 'Oberflächliches Gelaber' },
      { value: 'alcohol', label: 'Alkohol' },
      { value: 'screens', label: 'Bildschirm' },
      { value: 'stage', label: 'Vorne stehen, Karaoke, Impro' },
      { value: 'nothing', label: 'Nichts davon' },
    ],
    freeText: { placeholder: 'Sonst noch was? Allergie, Verletzung, …' },
    required: true,
    aggregation: 'union',
  },
  {
    id: 'q16_word',
    block: 'D',
    type: 'text',
    label: 'Ein Wort',
    title: 'Ein Wort, das der Abend am Ende verdient haben soll.',
    hint: 'Optional. Das erste, das dir einfällt.',
    placeholder: 'z. B. leicht, warm, wild, still …',
    maxLength: 40,
    required: false,
    aggregation: 'text',
  },
  {
    id: 'q17_joker',
    block: 'D',
    type: 'text',
    label: 'Joker',
    title: 'Wenn du allein entscheiden dürftest, was würden wir heute machen?',
    hint: 'Optional. Alles erlaubt, auch Unvernünftiges.',
    placeholder: 'Deine Idee …',
    multiline: true,
    maxLength: 280,
    required: false,
    aggregation: 'text',
  },
]

export const NICKNAME_ID = 'q00_nickname'

export const blockNames: Record<Question['block'], string> = {
  '0': 'Start',
  A: 'Innenwetter',
  B: 'Bedürfnis',
  C: 'Form',
  D: 'Rahmen & Joker',
}
